export const GET_ERRORS = "GET_ERRORS";
export const GET_BUILDING_TASK = "GET_BUILDING_TASK";
export const GET_BUILDING_TASKS = "GET_BUILDING_TASKS";
export const DELETE_BUILDING_TASK = "DELETE_BUILDING_TASK";
